FROM python:3.12
 
WORKDIR /vpn-webapp

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY . /vpn-webapp

RUN chmod +x /vpn-webapp/docker-entrypoint.sh

ENTRYPOINT ["/vpn-webapp/docker-entrypoint.sh"]
CMD ["python3.12", "app.py"]
